Numpy

In [18]:
import numpy as np

#Array creation: Conversion from other Python structures

In [19]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
listarray.dtype

dtype('int32')

In [22]:
listarray.size

9

In [23]:
listarray.shape

(3, 3)

In [24]:
zeros = np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
rng = np.arange(15+1)

In [29]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
lspace = np.linspace(1,4,5)

In [35]:
lspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [36]:
emp = np.empty((4,6))

In [38]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56602523e-307, 9.34605037e-307, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306, 2.22518251e-306],
       [1.33511969e-306, 1.78022342e-306, 1.05700345e-307,
        3.11525958e-307, 1.69118108e-306, 8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.29062229e-306,
        6.89804133e-307, 1.11261162e-306, 8.34443015e-308]])

In [39]:
ide = np.identity(45)

In [40]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [41]:
ide.shape

(45, 45)

In [42]:
arr = np.arange(99)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [46]:
arr = arr.reshape(3,33)

In [47]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [50]:
arr = arr.ravel()

In [51]:
arr.shape

(99,)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [53]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [54]:
ar = np.array(x)

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar.sum(axis=0)

array([12,  8,  9])

In [57]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [58]:
ar.flat

In [59]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [60]:
ar.ndim

2

In [61]:
ar.size

9

In [62]:
ar.nbytes

36