Numpy

In [18]:
import numpy as np

#Array creation: Conversion from other Python structures

In [19]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
listarray.dtype

dtype('int32')

In [22]:
listarray.size

9

In [23]:
listarray.shape

(3, 3)

In [24]:
zeros = np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
rng = np.arange(15+1)

In [29]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
lspace = np.linspace(1,50,10)

In [31]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])