Numpy

In [18]:
import numpy as np

#Array creation: Conversion from other Python structures

In [19]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
listarray.dtype

dtype('int32')

In [22]:
listarray.size

9

In [23]:
listarray.shape

(3, 3)

In [24]:
zeros = np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
rng = np.arange(15+1)

In [29]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
lspace = np.linspace(1,4,5)

In [35]:
lspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [36]:
emp = np.empty((4,6))

In [38]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56602523e-307, 9.34605037e-307, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306, 2.22518251e-306],
       [1.33511969e-306, 1.78022342e-306, 1.05700345e-307,
        3.11525958e-307, 1.69118108e-306, 8.06632139e-308],
       [1.20160711e-306, 1.69119330e-306, 1.29062229e-306,
        6.89804133e-307, 1.11261162e-306, 8.34443015e-308]])

In [39]:
ide = np.identity(45)

In [40]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])